[build]
  command = "cd simple-shop-app && npm install && ng build --configuration production && ng run simple-shop-app:server:production"
  publish = "simple-shop-app/dist/simple-shop-app/browser"
  functions = "simple-shop-app/netlify/functions"
