[build]
  command = "cd simple-shop-app && npm install && ng build --configuration production"
  publish = "simple-shop-app/dist/simple-shop-app/browser"  # Corrected to relative path
  functions = "simple-shop-app/netlify/functions"
