[build]
  command = "cd simple-shop-app && npm install && ng build --configuration production"
  publish = "/opt/build/repo/simple-shop-app/dist/simple-shop-app/browser"

[functions]
  directory = "/opt/build/repo/simple-shop-app/netlify/functions"
