[build]
  command = "npm install && npm run build && cp -r dist/simple-shop-app/server netlify/functions/"

  publish = "dist/simple-shop-app/browser"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[functions]]
  directory = "netlify/functions"
